#these values MUST remain the same as those in errors.h
OK=0
INVALID_BLOCK=10
CHAIN_MISMATCH=11
INVALID_TRANSACTION=12
BLOCK_NOT_FOUND=13
IPC_ERROR=20
CSV_PARSE_ERROR=21
FILE_ERROR=22
ARGS_ERROR=23
SYS_ERROR=30